version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: forum-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-forum}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  forum-api:
    build: .
    container_name: forum-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-forum}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  postgres_data:
